spring:
  application:
    name: mutilboard
  profiles:
    active: dev # 기본으로 dev 프로필 실행
  redis:
    host: localhost
    port: 6379

  messages:
    basename: msg/messages
    encoding: UTF-8
    cache-duration: PT1H

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true          # SQL 줄바꿈
        highlight_sql: true       # SQL 키워드 ANSI 색상
        use_sql_comments: true    # 쿼리 위 주석으로 JPQL 내용 출력

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret: NoOneCanKnowThisSuperSecretKeyForMultiBoardProjectForeverNeverShare
  expiration-time: 120000 #86400000
  #5sec : 5* 1000
  #1Min : 60 * 1000
  #1Hour : 60 * 1000
  #30Min : 30 * 60 * 1000 = 1800000